name: Python Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Build
      run: |
        chmod +x build.sh
        bash build.sh

    - name: Test
      run: |
        chmod +x test.sh
        bash test.sh
